module.exports = [
    {
        title:'高性能网站建设指南',
        path:'/high-performance-web-site/',
    },
    {
        title:'图解HTTP',
        path:'/illustration-HTTP/',
    },
    {
        title:'JavaScript函数式编程指南',
        path:'/functional-programming-in-javascript/',
    },
    {
        title:'JavaScript框架设计',
        path:'/javascript-framework-design/',
    },
    {
        title:'前端架构设计',
        path:'/front-end-architecture/'
    },
    {
        title:'web性能实战',
        path:'/web-performance-in-action/'
    }
]